#pragma once

char nfound[] = "HTTP/1.1 200 OK\r\n"
"Content-Type: text/html; charset=UTF-8\r\n\r\n"
"<!doctype html>"
"<html lang=\"en\">"
"<head>"
"<meta charset=\"utf - 8\">"
"<title>Controller's config</title>"
"</head>"
"<body>404</body>\r\n\0";

char page[] = "HTTP/1.1 200 OK\r\n"
"Content-Type: text/html; charset=UTF-8\r\n\r\n"
"<!doctype html>"
"<html lang=\"en\">"
"<head>"
"<meta charset=\"utf - 8\">"
"<title>Controller's config</title>"
"<style >"
"body {"
"background-color: #FAFAFA;"
"}"
"form {"
"background-color: #01579B;"
"width: 200px;"
"display: block;"
"margin-left: auto;"
"margin-right: auto;"
"padding-left: 20px;"
"padding-right: 20px;"
"padding-top: 20px;"
"border: 2px solid #01579B;"
"border-radius: 10px;"
"}"
"p{"
"color: #FAFAFA;"
"padding: 0;"
"margin: 0;"
"}"
"h3, h4 {"
"border-bottom: 1px solid #FAFAFA;"
"padding-bottom: 5px;"
"color: #FAFAFA;"
"}"
"#btncnt{"
"display: flex;"
"justify-content: center;"
"align-items: center;"
"}"
"button{"
"width: 150px;"
"height: 40px;"
"margin-bottom: 20px;"
"}"
".none{"
"margin-bottom: 20px;"
"padding-bottom: 20px;"
"}"
"</style>"
"<script>"
"function load(){"
"showHideInput(document.getElementById('sel'));"
"}"
"function showHideInput(sel) {"
"var value = sel.value;"
"if(value==\"PID\"){"
"document.getElementById('ts').style.display = 'none';"
"document.getElementById('pid').style.display = 'block';"
"}"
"else if(value==\"Two State\")"
"{"
"document.getElementById('ts').style.display = 'block';"
"document.getElementById('pid').style.display = 'none';"
"}"
"else"
"{"
"document.getElementById('ts').style.display = 'none';"
"document.getElementById('pid').style.display = 'none';"
"}"
"};"
"</script>"
"</head>"
"<body onload=\"load()\">"
"<form autocomplete=\"off\">"
"<div>"
"<p>Setpoint:</p>"
"<input required name=\"setpoint\" value=\"%f\"><br/><br/>"
"</div>"
"<div>"
"<h3>Wifi config</h3>"
"<p>SSID:</p>"
"<input name=\"ssid\" value=\"%s\"><br/><br/>"
"<p>Password:</p>"
"<input type=\"password\" name=\"psk\" value=\"%s\"><br/>"
"</div>"
"<div>"
"<h3>MQTT config</h3>"
"<p>Broker IP:</p>"
"<input required name=\"brokerip\" value=\"%s\"><br/><br/>"
"<p>SP topic:</p>"
"<input required name=\"sptopic\" value=\"%s\"><br/><br/>"
"<p>PV topic:</p>"
"<input required name=\"pvtopic\" value=\"%s\"><br/>"
"</div>"
"<div>"
"<h3>Input peripheral config</h3>"
"<p>Input min value:</p>"
"<input required name=\"inputmin\" value=\"%f\"><br/><br/>"
"<p>Input max value:</p>"
"<input required name=\"inputmax\" value=\"%f\"><br/>"
"</div>"
"<div>"
"<h3>Output peripheral config</h3>"
"<p>Output min value:</p>"
"<input required name=\"outputmin\" value=\"%f\"><br/><br/>"
"<p>Output max value:</p>"
"<input required name=outputmax value=\"%f\"><br/>"
"</div>"
"<div>"
"<h3>Controller config</h3>"
"<select id=\"sel\" onchange=\"showHideInput(this)\" name=\"selectedcontroller\">"
"<option %s value=\"None\">None</option>"
"<option %s value=\"Two State\">Two State</option>"
"<option %s value=\"PID\">PID</option>"
"</select>"
"<div id=\"ts\">"
"<h4>Two State Controller config</h4>"
"<p>Toggle off error value:</p>"
"<input required name=\"tstoggleoff\" value=\"%f\"><br/><br/>"
"<p>Toggle on error value:</p>"
"<input required name=\"tstoggleon\" value=\"%f\"><br/><br/>"
"<p>Off output value:</p>"
"<input required name=\"tsoffoutput\" value=\"%f\"><br/><br/>"
"<p>On output value:</p>"
"<input required name=\"tsonoutput\" value=\"%f\"><br/><br/>"
"</div>"
"<div id=\"pid\">"
"<h4>PID Controller config</h4>"
"<p>Kp:</p>"
"<input required name=\"pidkp\" value=\"%f\"><br/><br/>"
"<p>Ki:</p>"
"<input required name=\"pidki\" value=\"%f\"><br/><br/>"
"<p>Kd:</p>"
"<input required name=\"pidkd\" value=\"%f\"><br/><br/>"
"<p>Lower output saturation</p>"
"<input required name=\"pidlowsat\" value=\"%f\"><br/><br/>"
"<p>Upper output saturation</p>"
"<input required name=\"pidupsat\" value=\"%f\"><br/><br/>"
"</div>"
"<div  class=\"none\">"
"</div>"
"</div>"
"<div id=\"btncnt\">"
"<button type=\"submit\">Apply</button>"
"</div>"
"</form>"
"</body>"
"</html>\r\n\0";